apiVersion : apps/v1
kind: Deployment
metadata:
  name: trackerapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trackerapp
  template:
    metadata:
      labels:
        app: trackerapp 
    spec:
      containers:
        - name: trackerapp 
          image: trackerappacrrepo.azurecr.io/trackerapp
          ports:
          - containerPort: 80
